using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebServiceCoreV2.Storage.Sql
{
    public class CommandGlobal
    {
        //Select
        public static string GetList { get; set; } = "SELECT  P.id AS \"ID\", P.valueP AS \"VALUE\"  FROM [personalBudgetAS].[dbo].[ParametricLists] AS P INNER JOIN [personalBudgetAS].[dbo].[NameLists] AS N ON [N].id = P.nameList AND N.nameOfList = @Param1";
        public static string GetPrivileges { get; set; } = "SELECT [role] AS \"ROLE\" FROM [personalBudgetAS].[dbo].[UserLdap] WHERE [username] = @Param1";
        public static string GetDay { get; set; } = "SELECT [id], [name], [dayOfWeek], [idWeek] FROM [personalBudgetAS].[dbo].[Day] WHERE [name] = @name AND [idWeek] = @idWeek;";
        public static string GetWeek { get; set; } = "SELECT [id] FROM [personalBudgetAS].[dbo].[Week] WHERE [name] = @week AND [idMonth] = @idMonth";
        public static string GetMonth { get; set; } = "SELECT [id] FROM [personalBudgetAS].[dbo].[Month] WHERE [valueInYear] = @month AND [year] = @year";
        public static string GetRegisterId { get; set; } = "SELECT [id] AS \"ID\" FROM [dbo].[RegisterBudget] WHERE [name] = @name AND [description] = @description AND [typeCatalogue] = @typeCatalogue AND [valuePay] = @valuePay AND [currency] = @currency AND [dateBuy] = @dateBuy AND [timezone] = @timezone AND [support] = @support AND [idUser] = (SELECT [id] FROM [personalBudgetAS].[dbo].[UserLdap] WHERE [username] = @username)";
        public static string GetRegByDay { get; set; } = "SELECT [id], [name], [description], [typeCatalogue], [valuePay], [currency], [dateBuy], [timezone], [support] FROM [personalBudgetAS].[dbo].[RegisterBudget] WHERE [id] IN (SELECT [idReg] FROM [personalBudgetAS].[dbo].[ConsolidateDay] WHERE [idDay] = @idDay);";
        public static string GetRegByWeek { get; set; } = "SELECT [id], [name], [description], [typeCatalogue], [valuePay], [currency], [dateBuy], [timezone], [support] FROM [personalBudgetAS].[dbo].[RegisterBudget] WHERE [id] IN (SELECT [idReg] FROM [personalBudgetAS].[dbo].[ConsolidateWeek] WHERE [idWeek] = @idWeek);";
        public static string GetRegByMonth { get; set; } = "SELECT [id], [name], [description], [typeCatalogue], [valuePay], [currency], [dateBuy], [timezone], [support] FROM [personalBudgetAS].[dbo].[RegisterBudget] WHERE [id] IN (SELECT [idReg] FROM [personalBudgetAS].[dbo].[ConsolidateMonth] WHERE [idMonth] = @idMonth);";
        public static string GetRegById { get; set; } = "SELECT [id], [name], [description], [typeCatalogue], [valuePay], [currency], [dateBuy], [timezone], [support] FROM [personalBudgetAS].[dbo].[RegisterBudget] WHERE [id] = @id;";
        public static string GetProperty { get; set; } = "SELECT [value] FROM [personalBudgetAS].[dbo].[OptionApp] WHERE [name] = @Param1;";

        // Charts
        public static string GetTotalCurrency { get; } = "SELECT [R].[currency] AS 'CURRENCY', SUM([R].valuePay) AS 'TOTAL' FROM [personalBudgetAS].[dbo].[RegisterBudget] AS [R] WHERE [R].idUser = (SELECT [U].[id] FROM [personalBudgetAS].[dbo].[UserLdap] AS [U] WHERE [U].username = @username) GROUP BY [R].[currency];";
        public static string GetTotalCurrencyByDay { get; } = "SELECT [R].[currency] AS 'CURRENCY', SUM([R].valuePay) AS 'TOTAL' FROM [personalBudgetAS].[dbo].[RegisterBudget] AS [R] INNER JOIN [personalBudgetAS].[dbo].[ConsolidateDay] AS [CD] ON [CD].idReg = [R].id INNER JOIN [personalBudgetAS].[dbo].[Day] AS [D] ON [CD].idDay = [D].id AND [D].id = @id AND [R].idUser = (SELECT [U].[id] FROM [personalBudgetAS].[dbo].[UserLdap] AS [U] WHERE [U].username = @username) GROUP BY [R].[currency];";
        public static string GetTotalCurrencyByWeek { get; } = "SELECT [R].[currency] AS 'CURRENCY', SUM([R].valuePay) AS 'TOTAL' FROM [personalBudgetAS].[dbo].[RegisterBudget] AS [R] INNER JOIN [personalBudgetAS].[dbo].[ConsolidateWeek] AS [CW] ON [CW].idReg = [R].id INNER JOIN [personalBudgetAS].[dbo].[Week] AS [W] ON [CW].idWeek = [W].id AND [W].id = @id AND [R].idUser = (SELECT [U].[id] FROM [personalBudgetAS].[dbo].[UserLdap] AS [U] WHERE [U].username = @username) GROUP BY [R].[currency];";
        public static string GetTotalCurrencyByMonth { get; } = "SELECT [R].[currency] AS 'CURRENCY', SUM([R].valuePay) AS 'TOTAL' FROM [personalBudgetAS].[dbo].[RegisterBudget] AS [R]  INNER JOIN [personalBudgetAS].[dbo].[ConsolidateMonth] AS [CM] ON [CM].idReg = [R].id INNER JOIN [personalBudgetAS].[dbo].[Month] AS [M] ON [CM].idMonth = [M].id AND [M].id = @id AND [R].idUser = (SELECT [U].[id] FROM [personalBudgetAS].[dbo].[UserLdap] AS [U] WHERE [U].username = @username) GROUP BY [R].[currency];";

        public static string GetCountCurrency { get; } = "SELECT [R].[currency] AS 'CURRENCY', COUNT(*) AS 'TOTAL' FROM [personalBudgetAS].[dbo].[RegisterBudget] AS [R] WHERE [R].idUser = (SELECT [U].[id] FROM [personalBudgetAS].[dbo].[UserLdap] AS [U] WHERE [U].username = @username) GROUP BY [R].[currency];";
        public static string GetCountCurrencyByDay { get; } = "SELECT [R].[currency] AS 'CURRENCY', COUNT(*) AS 'TOTAL' FROM [personalBudgetAS].[dbo].[RegisterBudget] AS [R] INNER JOIN [personalBudgetAS].[dbo].[ConsolidateDay] AS [CD] ON [CD].idReg = [R].id INNER JOIN [personalBudgetAS].[dbo].[Day] AS [D] ON [CD].idDay = [D].id AND [D].id = @id AND [R].idUser = (SELECT [U].[id] FROM [personalBudgetAS].[dbo].[UserLdap] AS [U] WHERE [U].username = @username) GROUP BY [R].[currency];";
        public static string GetCountCurrencyByWeek { get; } = "SELECT [R].[currency] AS 'CURRENCY', COUNT(*) AS 'TOTAL' FROM [personalBudgetAS].[dbo].[RegisterBudget] AS [R] INNER JOIN [personalBudgetAS].[dbo].[ConsolidateWeek] AS [CW] ON [CW].idReg = [R].id INNER JOIN [personalBudgetAS].[dbo].[Week] AS [W] ON [CW].idWeek = [W].id AND [W].id = @id AND [R].idUser = (SELECT [U].[id] FROM [personalBudgetAS].[dbo].[UserLdap] AS [U] WHERE [U].username = @username) GROUP BY [R].[currency];";
        public static string GetCountCurrencyByMonth { get; } = "SELECT [R].[currency] AS 'CURRENCY', COUNT(*) AS 'TOTAL' FROM [personalBudgetAS].[dbo].[RegisterBudget] AS [R] INNER JOIN [personalBudgetAS].[dbo].[ConsolidateMonth] AS [CM] ON [CM].idReg = [R].id INNER JOIN [personalBudgetAS].[dbo].[Month] AS [M] ON [CM].idMonth = [M].id AND [M].id = @id AND [R].idUser = (SELECT [U].[id] FROM [personalBudgetAS].[dbo].[UserLdap] AS [U] WHERE [U].username = @username) GROUP BY [R].[currency];";


        public static string GetTotalDateBuy { get; set; } = "SELECT [R].[dateBuy] AS 'DATEBUY', SUM([R].[valuePay]) AS 'TOTAL' FROM [personalBudgetAS].[dbo].[RegisterBudget] AS [R] WHERE [R].idUser = (SELECT [U].[id] FROM [personalBudgetAS].[dbo].[UserLdap] AS [U] WHERE [U].username = @username) GROUP BY [R].[dateBuy];";
        public static string GetTotalDateBuyByDay { get; set; } = "SELECT [R].[dateBuy] AS 'DATEBUY', SUM([R].[valuePay]) AS 'TOTAL' FROM [personalBudgetAS].[dbo].[RegisterBudget] AS [R] INNER JOIN [personalBudgetAS].[dbo].[ConsolidateDay] AS [CD] ON [CD].idReg = [R].id INNER JOIN [personalBudgetAS].[dbo].[Day] AS [D] ON [CD].idDay = [D].id AND [D].id = @id AND [R].idUser = (SELECT [U].[id] FROM [personalBudgetAS].[dbo].[UserLdap] AS [U] WHERE [U].username = @username) GROUP BY [R].[dateBuy];";
        public static string GetTotalDateBuyByWeek { get; set; } = "SELECT [R].[dateBuy] AS 'DATEBUY', SUM([R].[valuePay]) AS 'TOTAL' FROM [personalBudgetAS].[dbo].[RegisterBudget] AS [R] INNER JOIN [personalBudgetAS].[dbo].[ConsolidateWeek] AS [CW] ON [CW].idReg = [R].id INNER JOIN [personalBudgetAS].[dbo].[Week] AS [W] ON [CW].idWeek = [W].id AND [W].id = @id AND [R].idUser = (SELECT [U].[id] FROM [personalBudgetAS].[dbo].[UserLdap] AS [U] WHERE [U].username = @username) GROUP BY [R].[dateBuy];";
        public static string GetTotalDateBuyByMonth { get; set; } = "SELECT [R].[dateBuy] AS 'DATEBUY', SUM([R].[valuePay]) AS 'TOTAL' FROM [personalBudgetAS].[dbo].[RegisterBudget] AS [R] INNER JOIN [personalBudgetAS].[dbo].[ConsolidateMonth] AS [CM] ON [CM].idReg = [R].id INNER JOIN [personalBudgetAS].[dbo].[Month] AS [M] ON [CM].idMonth = [M].id AND [M].id = @id AND [R].idUser = (SELECT [U].[id] FROM [personalBudgetAS].[dbo].[UserLdap] AS [U] WHERE [U].username = @username) GROUP BY [R].[dateBuy];";

        public static string GetCountDateBuy { get; set; } = "SELECT [R].[dateBuy] AS 'DATEBUY', COUNT(*) AS 'TOTAL' FROM [personalBudgetAS].[dbo].[RegisterBudget] AS [R] WHERE [R].idUser = (SELECT [U].[id] FROM [personalBudgetAS].[dbo].[UserLdap] AS [U] WHERE [U].username = @username) GROUP BY [R].[dateBuy];";
        public static string GetCountDateBuyByDay { get; set; } = "SELECT [R].[dateBuy] AS 'DATEBUY', COUNT(*) AS 'TOTAL' FROM [personalBudgetAS].[dbo].[RegisterBudget] AS [R] INNER JOIN [personalBudgetAS].[dbo].[ConsolidateDay] AS [CD] ON [CD].idReg = [R].id INNER JOIN [personalBudgetAS].[dbo].[Day] AS [D] ON [CD].idDay = [D].id AND [D].id = @id AND [R].idUser = (SELECT [U].[id] FROM [personalBudgetAS].[dbo].[UserLdap] AS [U] WHERE [U].username = @username)  GROUP BY [R].[dateBuy];";
        public static string GetCountDateBuyByWeek { get; set; } = "SELECT [R].[dateBuy] AS 'DATEBUY', COUNT(*) AS 'TOTAL' FROM [personalBudgetAS].[dbo].[RegisterBudget] AS [R] INNER JOIN [personalBudgetAS].[dbo].[ConsolidateWeek] AS [CW] ON [CW].idReg = [R].id INNER JOIN [personalBudgetAS].[dbo].[Week] AS [W] ON [CW].idWeek = [W].id AND [W].id = @id AND [R].idUser = (SELECT [U].[id] FROM [personalBudgetAS].[dbo].[UserLdap] AS [U] WHERE [U].username = @username) GROUP BY [R].[dateBuy];";
        public static string GetCountDateBuyByMonth { get; set; } = "SELECT [R].[dateBuy] AS 'DATEBUY', COUNT(*) AS 'TOTAL' FROM [personalBudgetAS].[dbo].[RegisterBudget] AS [R] INNER JOIN [personalBudgetAS].[dbo].[ConsolidateMonth] AS [CM] ON [CM].idReg = [R].id INNER JOIN [personalBudgetAS].[dbo].[Month] AS [M] ON [CM].idMonth = [M].id AND [M].id = @id AND [R].idUser = (SELECT [U].[id] FROM [personalBudgetAS].[dbo].[UserLdap] AS [U] WHERE [U].username = @username) GROUP BY [R].[dateBuy];";


        public static string GetTotalTimezone { get; set; } = "SELECT [R].[timezone] AS 'TIMEZONE', SUM([R].[valuePay]) AS 'TOTAL' FROM [personalBudgetAS].[dbo].[RegisterBudget] AS [R] WHERE [R].idUser = (SELECT [U].[id] FROM [personalBudgetAS].[dbo].[UserLdap] AS [U] WHERE [U].username = @username) GROUP BY [R].[timezone];";
        public static string GetTotalTimezoneByDay { get; set; } = "SELECT [R].[timezone] AS 'TIMEZONE', SUM([R].[valuePay]) AS 'TOTAL' FROM [personalBudgetAS].[dbo].[RegisterBudget] AS [R] INNER JOIN [personalBudgetAS].[dbo].[ConsolidateDay] AS [CD] ON [CD].idReg = [R].id INNER JOIN [personalBudgetAS].[dbo].[Day] AS [D] ON [CD].idDay = [D].id AND [D].id = @id AND [R].idUser = (SELECT [U].[id] FROM [personalBudgetAS].[dbo].[UserLdap] AS [U] WHERE [U].username = @username) GROUP BY [R].[timezone];";
        public static string GetTotalTimezoneByWeek { get; set; } = "SELECT [R].[timezone] AS 'TIMEZONE', SUM([R].[valuePay]) AS 'TOTAL' FROM [personalBudgetAS].[dbo].[RegisterBudget] AS [R] INNER JOIN [personalBudgetAS].[dbo].[ConsolidateWeek] AS [CW] ON [CW].idReg = [R].id INNER JOIN [personalBudgetAS].[dbo].[Week] AS [W] ON [CW].idWeek = [W].id AND [W].id = @id AND [R].idUser = (SELECT [U].[id] FROM [personalBudgetAS].[dbo].[UserLdap] AS [U] WHERE [U].username = @username) GROUP BY [R].[timezone];";
        public static string GetTotalTimezoneByMonth { get; set; } = "SELECT [R].[timezone] AS 'TIMEZONE', SUM([R].[valuePay]) AS 'TOTAL' FROM [personalBudgetAS].[dbo].[RegisterBudget] AS [R] INNER JOIN [personalBudgetAS].[dbo].[ConsolidateMonth] AS [CM] ON [CM].idReg = [R].id INNER JOIN [personalBudgetAS].[dbo].[Month] AS [M] ON [CM].idMonth = [M].id AND [M].id = @id AND [R].idUser = (SELECT [U].[id] FROM [personalBudgetAS].[dbo].[UserLdap] AS [U] WHERE [U].username = @username) GROUP BY [R].[timezone];";

        public static string GetCountTimezone { get; set; } = "SELECT [R].[timezone] AS 'TIMEZONE', COUNT(*) AS 'TOTAL' FROM [personalBudgetAS].[dbo].[RegisterBudget] AS [R] WHERE [R].idUser = (SELECT [U].[id] FROM [personalBudgetAS].[dbo].[UserLdap] AS [U] WHERE [U].username = @username) GROUP BY [R].[timezone];";
        public static string GetCountTimezoneByDay { get; set; } = "SELECT [R].[timezone] AS 'TIMEZONE', COUNT(*) AS 'TOTAL' FROM [personalBudgetAS].[dbo].[RegisterBudget] AS [R] INNER JOIN [personalBudgetAS].[dbo].[ConsolidateDay] AS [CD] ON [CD].idReg = [R].id INNER JOIN [personalBudgetAS].[dbo].[Day] AS [D] ON [CD].idDay = [D].id AND [D].id = @id AND [R].idUser = (SELECT [U].[id] FROM [personalBudgetAS].[dbo].[UserLdap] AS [U] WHERE [U].username = @username) GROUP BY [R].[timezone];";
        public static string GetCountTimezoneByWeek { get; set; } = "SELECT [R].[timezone] AS 'TIMEZONE', COUNT(*) AS 'TOTAL' FROM [personalBudgetAS].[dbo].[RegisterBudget] AS [R] INNER JOIN [personalBudgetAS].[dbo].[ConsolidateWeek] AS [CW] ON [CW].idReg = [R].id INNER JOIN [personalBudgetAS].[dbo].[Week] AS [W] ON [CW].idWeek = [W].id AND [W].id = @id AND [R].idUser = (SELECT [U].[id] FROM [personalBudgetAS].[dbo].[UserLdap] AS [U] WHERE [U].username = @username) GROUP BY [R].[timezone];";
        public static string GetCountTimezoneByMonth { get; set; } = "SELECT [R].[timezone] AS 'TIMEZONE', COUNT(*) AS 'TOTAL' FROM [personalBudgetAS].[dbo].[RegisterBudget] AS [R] INNER JOIN [personalBudgetAS].[dbo].[ConsolidateMonth] AS [CM] ON [CM].idReg = [R].id INNER JOIN [personalBudgetAS].[dbo].[Month] AS [M] ON [CM].idMonth = [M].id AND [M].id = @id AND [R].idUser = (SELECT [U].[id] FROM [personalBudgetAS].[dbo].[UserLdap] AS [U] WHERE [U].username = @username) GROUP BY [R].[timezone];";


        public static string GetTotalTypeCatalogue { get; set; } = "SELECT [R].[typeCatalogue] AS 'TYPECALOGUE', SUM([R].[valuePay]) AS 'TOTAL' FROM [personalBudgetAS].[dbo].[RegisterBudget] AS [R] WHERE [R].idUser = (SELECT [U].[id] FROM [personalBudgetAS].[dbo].[UserLdap] AS [U] WHERE [U].username = @username) GROUP BY [R].[typeCatalogue];";
        public static string GetTotalTypeCatalogueByDay { get; set; } = "SELECT [R].[typeCatalogue] AS 'TYPECALOGUE', SUM([R].[valuePay]) AS 'TOTAL' FROM [personalBudgetAS].[dbo].[RegisterBudget] AS [R] INNER JOIN [personalBudgetAS].[dbo].[ConsolidateDay] AS [CD] ON [CD].idReg = [R].id INNER JOIN [personalBudgetAS].[dbo].[Day] AS [D] ON [CD].idDay = [D].id AND [D].id = @id AND [R].idUser = (SELECT [U].[id] FROM [personalBudgetAS].[dbo].[UserLdap] AS [U] WHERE [U].username = @username) GROUP BY [R].[typeCatalogue];";
        public static string GetTotalTypeCatalogueByWeek { get; set; } = "SELECT [R].[typeCatalogue] AS 'TYPECALOGUE', SUM([R].[valuePay]) AS 'TOTAL' FROM [personalBudgetAS].[dbo].[RegisterBudget] AS [R] INNER JOIN [personalBudgetAS].[dbo].[ConsolidateWeek] AS [CW] ON [CW].idReg = [R].id INNER JOIN [personalBudgetAS].[dbo].[Week] AS [W] ON [CW].idWeek = [W].id AND [W].id = @id AND [R].idUser = (SELECT [U].[id] FROM [personalBudgetAS].[dbo].[UserLdap] AS [U] WHERE [U].username = @username) GROUP BY [R].[typeCatalogue];";
        public static string GetTotalTypeCatalogueByMonth { get; set; } = "SELECT [R].[typeCatalogue] AS 'TYPECALOGUE', SUM([R].[valuePay]) AS 'TOTAL' FROM [personalBudgetAS].[dbo].[RegisterBudget] AS [R] INNER JOIN [personalBudgetAS].[dbo].[ConsolidateMonth] AS [CM] ON [CM].idReg = [R].id INNER JOIN [personalBudgetAS].[dbo].[Month] AS [M] ON [CM].idMonth = [M].id AND [M].id = @id AND [R].idUser = (SELECT [U].[id] FROM [personalBudgetAS].[dbo].[UserLdap] AS [U] WHERE [U].username = @username) GROUP BY [R].[typeCatalogue];";

        public static string GetCountTypeCatalogue { get; set; } = "SELECT [R].[typeCatalogue] AS 'TYPECALOGUE', COUNT(*) AS 'TOTAL' FROM [personalBudgetAS].[dbo].[RegisterBudget] AS [R] WHERE [R].idUser = (SELECT [U].[id] FROM [personalBudgetAS].[dbo].[UserLdap] AS [U] WHERE [U].username = @username) GROUP BY [R].[typeCatalogue];";
        public static string GetCountTypeCatalogueByDay { get; set; } = "SELECT [R].[typeCatalogue] AS 'TYPECALOGUE', COUNT(*) AS 'TOTAL' FROM [personalBudgetAS].[dbo].[RegisterBudget] AS [R] INNER JOIN [personalBudgetAS].[dbo].[ConsolidateDay] AS [CD] ON [CD].idReg = [R].id INNER JOIN [personalBudgetAS].[dbo].[Day] AS [D] ON [CD].idDay = [D].id AND [D].id = @id AND [R].idUser = (SELECT [U].[id] FROM [personalBudgetAS].[dbo].[UserLdap] AS [U] WHERE [U].username = @username) GROUP BY [R].[typeCatalogue];";
        public static string GetCountTypeCatalogueByWeek { get; set; } = "SELECT [R].[typeCatalogue] AS 'TYPECALOGUE', COUNT(*) AS 'TOTAL' FROM [personalBudgetAS].[dbo].[RegisterBudget] AS [R] INNER JOIN [personalBudgetAS].[dbo].[ConsolidateWeek] AS [CW] ON [CW].idReg = [R].id INNER JOIN [personalBudgetAS].[dbo].[Week] AS [W] ON [CW].idWeek = [W].id AND [W].id = @id AND [R].idUser = (SELECT [U].[id] FROM [personalBudgetAS].[dbo].[UserLdap] AS [U] WHERE [U].username = @username) GROUP BY [R].[typeCatalogue];";
        public static string GetCountTypeCatalogueByMonth { get; set; } = "SELECT [R].[typeCatalogue] AS 'TYPECALOGUE', COUNT(*) AS 'TOTAL' FROM [personalBudgetAS].[dbo].[RegisterBudget] AS [R] INNER JOIN [personalBudgetAS].[dbo].[ConsolidateMonth] AS [CM] ON [CM].idReg = [R].id INNER JOIN [personalBudgetAS].[dbo].[Month] AS [M] ON [CM].idMonth = [M].id AND [M].id = @id AND [R].idUser = (SELECT [U].[id] FROM [personalBudgetAS].[dbo].[UserLdap] AS [U] WHERE [U].username = @username) GROUP BY [R].[typeCatalogue];";


        //Insert
        public static string InsertPayment { get; set; } = "INSERT INTO [personalBudgetAS].[dbo].[RegisterBudget] ([name], [description], [typeCatalogue], [valuePay], [currency], [dateBuy], [timezone], [support], [idUser]) VALUES (@name, @description, @typeCatalogue, @valuePay, @currency, @dateBuy, @timezone, @support, (SELECT [id] FROM [personalBudgetAS].[dbo].[UserLdap] WHERE [username] = @username))";
        public static string InsertPaymentDay { get; set; } = "INSERT INTO [personalBudgetAS].[dbo].[ConsolidateDay] ([idDay], [idReg]) VALUES ( @day , @reg )";
        public static string InsertPaymentWeek { get; set; } = "INSERT INTO [personalBudgetAS].[dbo].[ConsolidateWeek] ([idWeek], [idReg]) VALUES ( @week, @reg )";
        public static string InsertPaymentMonth { get; set; } = "INSERT INTO [personalBudgetAS].[dbo].[ConsolidateMonth] ([idMonth],[idReg]) VALUES ( @month, @reg )";
        public static string InsertDay { get; set; } = "INSERT INTO [personalBudgetAS].[dbo].[Day] ([name], [dayOfWeek], [idWeek]) VALUES (@name, @dayOfWeek, @idWeek)";
        public static string InsertWeek { get; set; } = "INSERT INTO [personalBudgetAS].[dbo].[Week] ([name], [valueInMonth], [idMonth]) VALUES (@nameWeek, @valueInMonth, @idMonth)";
        public static string InsertMonth { get; set; } = "INSERT INTO [personalBudgetAS].[dbo].[Month] ([name], [valueInYear], [year]) VALUES (@name, @valueInYear, @year)";
        public static string InsertRegToken { get; set; } = "INSERT INTO [personalBudgetAS].[dbo].[Token] ([tokenName], [duration], [tokenDateUser], [idUser], [idApp]) VALUES (@tokenName, @duration, @tokenDateUser, (SELECT [id] FROM [personalBudgetAS].[dbo].[UserLdap] WHERE [username] = @username), (SELECT [id] FROM [personalBudgetAS].[dbo].[ApplicationCore] WHERE [nameApp] = @nameApp));";

        //Update
        public static string UpdatePayment { get; set; } = "UPDATE [personalBudgetAS].[dbo].[RegisterBudget] SET ";
        // public static string UpdatePaymentDay { get; set; } = "UPDATE [personalBudgetAS].[dbo].[ConsolidateDay] ";
        // public static string UpdatePaymentWeek { get; set; } = "UPDATE [personalBudgetAS].[dbo].[ConsolidateWeek] ";
        // public static string UpdatePaymentMonth { get; set; } = "UPDATE [personalBudgetAS].[dbo].[ConsolidateMonth] ";

        //Delete
        public static string DeleteRegister { get; set; } = "DELETE FROM [personalBudgetAS].[dbo].[RegisterBudget] WHERE [id] = @id;";
        public static string DeletePaymentDay { get; set; } = "DELETE FROM [personalBudgetAS].[dbo].[ConsolidateDay] WHERE [idReg] = @idReg;";
        public static string DeletePaymentWeek { get; set; } = "DELETE FROM [personalBudgetAS].[dbo].[ConsolidateWeek] WHERE [idReg] = @idReg;";
        public static string DeletePaymentMonth { get; set; } = "DELETE FROM [personalBudgetAS].[dbo].[ConsolidateMonth] WHERE [idReg] = @idReg;";
    }
}
